spring.application.name=foodapp-backend
spring.datasource.url=jdbc:mysql://localhost:3306/FoodApp
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.com.foodapp.backend.security.JwtFilter=DEBUG 
logging.level.org.springframework.security=DEBUG  
